version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: todolist-db
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: eryck@3003
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todolist-network

  app:
    build: .  # ← Constrói usando o Dockerfile na pasta atual
    container_name: todolist-app
    depends_on:
      - postgres
    ports:
      - "9191:9191"
    environment:
      # Configurações do banco (sobrescreve o application.yml)
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/todolist
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: teste@123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    networks:
      - todolist-network

volumes:
  postgres_data:

networks:
  todolist-network:
    driver: bridge
