server:
  port: 9191
  servlet:
    context-path: /api
spring:
  name: toDo-List
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/todolist}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:eryck@3003}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true                    # ← Liga o Flyway
    locations: classpath:db/migration # ← Pasta das migrations
    baseline-on-migrate: true        # ← Permite banco existente
    validate-on-migrate: true        # ← Valida antes de aplicar
    clean-disabled: true             # ← Impede flyway:clean (segurança)
    out-of-order: false
  jpa:
    hibernate:
      ddl-auto: validate # Pode ser none, validate, update, create, create-drop
    show-sql: false # Mostra as queries no console
    properties:
      hibernate:
        format_sql: false
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    root: INFO
    org.hibernate.orm.connections.pooling: OFF
  pattern:
    console: "%clr(%d{dd/MM/yyyy HH:mm:ss.SSS}){blue} %clr([%1.15t]){magenta} - %clr(%-5level){highlight} - %clr([%-30.30logger{29}]){cyan} %clr(→){white} %clr(%msg){yellow}%n%clr(%ex){red bold}"