server:
  port: 9191
  servlet:
    context-path: /api
spring:
  name: toDo-List
  datasource:
    url: ${SPRING_DATASOURCE_URL:url}
    username: ${SPRING_DATASOURCE_USERNAME:username}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true                    # ← Liga o Flyway
    locations: classpath:db/migration # ← Pasta das migrations
    baseline-on-migrate: true        # ← Permite banco existente
    validate-on-migrate: true        # ← Valida antes de aplicar
    clean-disabled: true             # ← Impede flyway:clean (segurança)
    out-of-order: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate # Pode ser none, validate, update, create, create-drop
    show-sql: false # Mostra as queries no console
    properties:
      hibernate:
        format_sql: false
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    org.flywaydb.core: OFF
    org.hibernate.orm.connections.pooling: OFF
  pattern:
    console: "%clr(%d{dd/MM/yyyy HH:mm:ss.SSS}){blue} %clr([%1.15t]){magenta} - %clr(%-5level){highlight} - %clr([%-30.30logger{29}]){cyan} %clr(→){white} %clr(%msg){yellow}%n%clr(%ex){red bold}"
springdoc:
  enable-hateoas: true
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    layout: StandaloneLayout
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
    docExpansion: none
    tryItOutEnabled: true